language: python
matrix:
  include:
    - python: 2.7
      env: TESTENV=py27-pytest2
    - python: 2.7
      env: TESTENV=py27-pytest3
    - python: 3.4
      env: TESTENV=py34-pytest2
    - python: 3.4
      env: TESTENV=py34-pytest3
    - python: 3.5
      env: TESTENV=py35-pytest2
    - python: 3.5
      env: TESTENV=py35-pytest3
    - python: 3.6
      env: TESTENV=py36-pytest2
    - python: 3.6
      env: TESTENV=py36-pytest3
    - python: 3.7-dev
      env: TESTENV=py37-pytest2
    - python: 3.7-dev
      env: TESTENV=py37-pytest3
install:
  - pip install -U tox
script:
  - tox --recreate -e $TESTENV
